name: Test CMake Project on Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ make git

      - name: Install latest CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/Kitware/CMake/releases/download/v4.1.1/cmake-4.1.1-linux-x86_64.sh
          sudo mkdir /opt/cmake
          sudo sh cmake-4.1.1-linux-x86_64.sh --skip-license --prefix=/opt/cmake
          echo "/opt/cmake/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
